# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 971171250ffa38f59018ce7574f1e2f12e866428960d6925050a20283bdf7cfbdb06a99db9ac8eed18cbed78fe10ba8a1cb4350e9949bf28a8e30097432411f0

test:
  secret_key_base: d40e1686dc5b491bbac87978675ee35764413ebe7081da3cdd84ef20fcf7b8c6b99a0b1830c0d5bc454b9f20436506f30225e8372745c9a0022e15b0a236fea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
